cluster:
  mkdir -p log/{rule} &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}
    --output=log/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.runtime}
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-envmodules: True
cluster-status: status-sacct.sh
cluster-cancel: "scancel"
